services:
  database:
    image: postgres:17.2-alpine
    build:
      context: .
      dockerfile: ./postgre-db/Dockerfile        
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}    
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - network
    restart: always      


  app:   
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./src:/usr/app/src
      - /app/node_modules    
    networks:
      - network    
    
volumes:
  postgres_data:
  postgres_logs:  

networks:
  network:
    driver: bridge