networks:
  hls-network:
    driver: bridge

services:
  app:
    container_name: hls-app
    image: nodejs2024q3service:latest
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - hls-network
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: hls-postgres
    image: nodejs2024q3service-db:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - hls-network
    restart: always

volumes:
  postgres_data:
  postgres_logs:
